version: "3"
services:

  web:
    container_name: web-dev
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    links:
      - mysql:db
    cap_add:
    - SYS_PTRACE
    privileged: true
    env_file: .env

  mysql:
    container_name: sql-dev
    image: warmiak/percona5.7
    ports:
      - "33006:3306"
    volumes:
      - mysql-disk:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dockerphp
      - MYSQL_ROOT_PASSWORD=password

volumes:
  mysql-disk: